"""add_chat_context_fields

Revision ID: 155d5d9380f5
Revises: ea5251f8fbae
Create Date: 2025-12-05 23:45:07.151096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155d5d9380f5'
down_revision = 'ea5251f8fbae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_threads', sa.Column('type', sa.String(length=50), nullable=False, server_default='general'))
    op.add_column('chat_threads', sa.Column('process_code', sa.String(length=50), nullable=True))
    op.add_column('chat_threads', sa.Column('process_id', sa.Integer(), nullable=True))
    op.add_column('chat_threads', sa.Column('law_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_threads_process_code'), 'chat_threads', ['process_code'], unique=False)
    op.create_index(op.f('ix_chat_threads_type'), 'chat_threads', ['type'], unique=False)
    op.create_foreign_key(None, 'chat_threads', 'processes', ['process_id'], ['id'])
    op.create_foreign_key(None, 'chat_threads', 'legislations', ['law_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_threads', type_='foreignkey')
    op.drop_constraint(None, 'chat_threads', type_='foreignkey')
    op.drop_index(op.f('ix_chat_threads_type'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_process_code'), table_name='chat_threads')
    op.drop_column('chat_threads', 'law_id')
    op.drop_column('chat_threads', 'process_id')
    op.drop_column('chat_threads', 'process_code')
    op.drop_column('chat_threads', 'type')
    # ### end Alembic commands ###
