"""add process_id to documents

Revision ID: 18e93104c3be
Revises: 8c9826281c3e
Create Date: 2026-01-15 21:28:41.071682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e93104c3be'
down_revision = '8c9826281c3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'processes', ['process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'process_id')
    # ### end Alembic commands ###
