"""add_agenda_documents_legislations_processes_tables

Revision ID: 25f9330d6de4
Revises: f42f49bda1a1
Create Date: 2025-11-29 13:32:56.367764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f9330d6de4'
down_revision = 'f42f49bda1a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('VIGENTE', 'REVOGADA', 'EM_ATUALIZACAO', name='legislationstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('jurisdiction_scope', sa.Enum('FEDERAL', 'ESTADUAL', 'MUNICIPAL', name='jurisdictionscope'), nullable=False),
    sa.Column('jurisdiction_state', sa.String(length=2), nullable=True),
    sa.Column('jurisdiction_city', sa.String(length=255), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('reference_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('compliance_level', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='compliancelevel'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislations_id'), 'legislations', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('VALIDADO', 'PENDENTE', 'EXPIRADO', 'EM_ANALISE', name='documentstatus'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('encryption_iv', sa.String(length=64), nullable=True),
    sa.Column('encryption_tag', sa.String(length=64), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'AGUARDANDO_ANALISE', 'APROVADO', 'PENDENTE', 'ATRASADO', 'CANCELADO', name='processstatus'), nullable=False),
    sa.Column('priority', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='processpriority'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol')
    )
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_table('agenda_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'ATRASADO', name='agendastatus'), nullable=False),
    sa.Column('priority', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'CRITICA', name='agendapriority'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('related_process_id', sa.Integer(), nullable=True),
    sa.Column('related_document_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['related_process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_events_id'), 'agenda_events', ['id'], unique=False)
    op.create_table('process_timeline_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'AGUARDANDO_ANALISE', 'APROVADO', 'PENDENTE', 'ATRASADO', 'CANCELADO', name='processstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_timeline_entries_id'), 'process_timeline_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_timeline_entries_id'), table_name='process_timeline_entries')
    op.drop_table('process_timeline_entries')
    op.drop_index(op.f('ix_agenda_events_id'), table_name='agenda_events')
    op.drop_table('agenda_events')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_legislations_id'), table_name='legislations')
    op.drop_table('legislations')
    # ### end Alembic commands ###
