"""add parent_id to checklist items

Revision ID: 545e8aab4deb
Revises: 18e93104c3be
Create Date: 2026-01-15 21:39:06.458508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545e8aab4deb'
down_revision = '18e93104c3be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_checklist_items', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'process_checklist_items', 'process_checklist_items', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'process_checklist_items', type_='foreignkey')
    op.drop_column('process_checklist_items', 'parent_id')
    # ### end Alembic commands ###
