"""Add chat files and timeline

Revision ID: 59ad7a332a1f
Revises: a1b2c3d4e5f6
Create Date: 2025-11-13 22:14:27.080163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59ad7a332a1f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Helper function to safely drop indexes and tables using SQL
    connection = op.get_bind()
    
    def safe_drop_index(index_name, table_name):
        connection.execute(sa.text(f'DROP INDEX IF EXISTS "{index_name}"'))
    
    def safe_drop_table(table_name):
        # Escape table name with quotes (needed for reserved words like 'user')
        connection.execute(sa.text(f'DROP TABLE IF EXISTS "{table_name}" CASCADE'))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('encryption_iv', sa.String(length=255), nullable=False),
    sa.Column('encryption_tag', sa.String(length=255), nullable=False),
    sa.Column('encryption_algo', sa.String(length=50), nullable=False),
    sa.Column('key_version', sa.String(length=50), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_files_created_at'), 'chat_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_files_id'), 'chat_files', ['id'], unique=False)
    op.create_index(op.f('ix_chat_files_organization_id'), 'chat_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_files_thread_id'), 'chat_files', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_files_user_id'), 'chat_files', ['user_id'], unique=False)
    op.create_table('chat_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STAGE', 'SYSTEM', 'FILE', 'DECISION', 'AI_PROCESSING', 'ERROR', name='timelineeventtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ERROR', 'CANCELLED', name='timelineeventstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_timeline_events_created_at'), 'chat_timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_id'), 'chat_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_order_index'), 'chat_timeline_events', ['order_index'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_organization_id'), 'chat_timeline_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_status'), 'chat_timeline_events', ['status'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_thread_id'), 'chat_timeline_events', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_timeline_events_type'), 'chat_timeline_events', ['type'], unique=False)
    # Drop N8N tables/indexes safely (they may not exist in fresh database)
    safe_drop_index('idx_812eb05f7451ca757fb98444ce', 'tag_entity')
    safe_drop_index('pk_tag_entity_id', 'tag_entity')
    safe_drop_table('tag_entity')
    safe_drop_index('IDX_8e4b4774db42f1e6dda3452b2a', 'test_case_execution')
    safe_drop_table('test_case_execution')
    safe_drop_table('data_table')
    safe_drop_index('IDX_workflow_entity_name', 'workflow_entity')
    safe_drop_index('pk_workflow_entity_id', 'workflow_entity')
    safe_drop_table('workflow_entity')
    safe_drop_index('IDX_cec8eea3bf49551482ccb4933e', 'execution_metadata')
    safe_drop_table('execution_metadata')
    safe_drop_table('installed_packages')
    safe_drop_index('IDX_14f68deffaf858465715995508', 'folder')
    safe_drop_table('folder')
    safe_drop_table('execution_data')
    safe_drop_table('shared_credentials')
    safe_drop_table('auth_identity')
    safe_drop_index('IDX_ae51b54c4bb430cf92f48b623f', 'annotation_tag_entity')
    safe_drop_table('annotation_tag_entity')
    safe_drop_index('IDX_60b6a84299eeb3f671dfec7693', 'insights_by_period')
    safe_drop_table('insights_by_period')
    safe_drop_index('IDX_role_scope_scopeSlug', 'role_scope')
    safe_drop_table('role_scope')
    safe_drop_index('pk_variables_id', 'variables')
    safe_drop_table('variables')
    safe_drop_index('idx_16f4436789e804e3e1c9eeb240', 'webhook_entity')
    safe_drop_table('webhook_entity')
    safe_drop_table('event_destinations')
    safe_drop_table('processed_data')
    safe_drop_table('role')
    safe_drop_index('idx_07fde106c0b471d8cc80a64fc8', 'credentials_entity')
    safe_drop_index('pk_credentials_entity_id', 'credentials_entity')
    safe_drop_table('credentials_entity')
    safe_drop_table('project')
    safe_drop_index('IDX_a3697779b366e131b2bbdae297', 'execution_annotation_tags')
    safe_drop_index('IDX_c1519757391996eb06064f0e7c', 'execution_annotation_tags')
    safe_drop_table('execution_annotation_tags')
    safe_drop_index('IDX_execution_entity_deletedAt', 'execution_entity')
    connection.execute(sa.text('DROP INDEX IF EXISTS idx_execution_entity_stopped_at_status_deleted_at'))
    connection.execute(sa.text('DROP INDEX IF EXISTS idx_execution_entity_wait_till_status_deleted_at'))
    connection.execute(sa.text('DROP INDEX IF EXISTS idx_execution_entity_workflow_id_started_at'))
    safe_drop_table('execution_entity')
    safe_drop_index('IDX_1d8ab99d5861c9388d2dc1cf73', 'insights_metadata')
    safe_drop_table('insights_metadata')
    safe_drop_table('folder_tag')
    safe_drop_index('IDX_1e31657f5fe46816c34be7c1b4', 'workflow_history')
    safe_drop_table('workflow_history')
    safe_drop_index('IDX_97f863fa83c4786f1956508496', 'execution_annotations')
    safe_drop_table('execution_annotations')
    safe_drop_index('IDX_1ef35bac35d20bdae979d917a3', 'user_api_keys')
    safe_drop_index('IDX_63d7bbae72c767cf162d459fcc', 'user_api_keys')
    safe_drop_table('user_api_keys')
    safe_drop_table('workflow_statistics')
    safe_drop_index('user_role_idx', 'user')
    safe_drop_table('user')
    safe_drop_table('data_table_column')
    safe_drop_table('migrations')
    safe_drop_table('auth_provider_sync_history')
    safe_drop_index('IDX_d6870d3b6e4c185d33926f423c', 'test_run')
    safe_drop_table('test_run')
    safe_drop_table('installed_nodes')
    safe_drop_table('insights_raw')
    safe_drop_table('invalid_auth_token')
    safe_drop_index('idx_workflows_tags_workflow_id', 'workflows_tags')
    safe_drop_table('workflows_tags')
    safe_drop_table('settings')
    safe_drop_index('IDX_5f0643f6717905a05164090dde', 'project_relation')
    safe_drop_index('IDX_61448d56d61802b5dfde5cdb00', 'project_relation')
    safe_drop_index('project_relation_role_idx', 'project_relation')
    safe_drop_index('project_relation_role_project_idx', 'project_relation')
    safe_drop_table('project_relation')
    safe_drop_table('scope')
    safe_drop_table('shared_workflow')
    # These indexes should exist - drop safely
    safe_drop_index('ix_user_org_assoc_org_id', 'user_organization_association')
    safe_drop_index('ix_user_org_assoc_user_id', 'user_organization_association')
    safe_drop_index('ix_users_last_organization_id', 'users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_last_organization_id', 'users', ['last_organization_id'], unique=False)
    op.create_index('ix_user_org_assoc_user_id', 'user_organization_association', ['user_id'], unique=False)
    op.create_index('ix_user_org_assoc_org_id', 'user_organization_association', ['organization_id'], unique=False)
    op.create_table('shared_workflow',
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_a45ea5f27bcfdc21af9b4188560', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='FK_daa206a04983d47d0a9c34649ce', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflowId', 'projectId', name='PK_5ba87620386b847201c9531c58f')
    )
    op.create_table('scope',
    sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='Unique identifier of the scope for example: "project:create"'),
    sa.Column('displayName', sa.TEXT(), autoincrement=False, nullable=True, comment='Name used to display in the UI'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Text describing the scope in more detail of users'),
    sa.PrimaryKeyConstraint('slug', name='PK_bfc45df0481abd7f355d6187da1'),
    postgresql_ignore_search_path=False
    )
    op.create_table('project_relation',
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_61448d56d61802b5dfde5cdb002', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['role.slug'], name='FK_c6b99592dc96b0d836d7a21db91'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='FK_5f0643f6717905a05164090dde7', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('projectId', 'userId', name='PK_1caaa312a5d7184a003be0f0cb6')
    )
    op.create_index('project_relation_role_project_idx', 'project_relation', ['projectId', 'role'], unique=False)
    op.create_index('project_relation_role_idx', 'project_relation', ['role'], unique=False)
    op.create_index('IDX_61448d56d61802b5dfde5cdb00', 'project_relation', ['projectId'], unique=False)
    op.create_index('IDX_5f0643f6717905a05164090dde', 'project_relation', ['userId'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('loadOnStartup', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='PK_dc0fe14e6d9943f268e7b119f69ab8bd')
    )
    op.create_table('workflows_tags',
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tagId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['tag_entity.id'], name='fk_workflows_tags_tag_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='fk_workflows_tags_workflow_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflowId', 'tagId', name='pk_workflows_tags')
    )
    op.create_index('idx_workflows_tags_workflow_id', 'workflows_tags', ['workflowId'], unique=False)
    op.create_table('invalid_auth_token',
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('token', name='PK_5779069b7235b256d91f7af1a15')
    )
    op.create_table('insights_raw',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('metaId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False, comment='0: time_saved_minutes, 1: runtime_milliseconds, 2: success, 3: failure'),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metaId'], ['insights_metadata.metaId'], name='FK_6e2e33741adef2a7c5d66befa4e', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_ec15125755151e3a7e00e00014f')
    )
    op.create_table('installed_nodes',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('latestVersion', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('package', sa.VARCHAR(length=241), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package'], ['installed_packages.packageName'], name='FK_73f857fc5dce682cef8a99c11dbddbc969618951', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', name='PK_8ebd28194e4f792f96b5933423fc439df97d9689')
    )
    op.create_table('test_run',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('errorCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('errorDetails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('runAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='FK_d6870d3b6e4c185d33926f423c8', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_011c050f566e9db509a0fadb9b9'),
    postgresql_ignore_search_path=False
    )
    op.create_index('IDX_d6870d3b6e4c185d33926f423c', 'test_run', ['workflowId'], unique=False)
    op.create_table('auth_provider_sync_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('providerType', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('runMode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('startedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('endedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('scanned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disabled', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='auth_provider_sync_history_pkey')
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_8c82d7f526340ab734260ea46be')
    )
    op.create_table('data_table_column',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='Expected: string, number, boolean, or date (not enforced as a constraint)'),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False, comment='Column order, starting from 0 (0 = first column)'),
    sa.Column('dataTableId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataTableId'], ['data_table.id'], name='FK_930b6e8faaf88294cef23484160', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_673cb121ee4a8a5e27850c72c51'),
    sa.UniqueConstraint('dataTableId', 'name', name='UQ_8082ec4890f892f0bc77473a123', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text("uuid_in((OVERLAY(OVERLAY(md5((((random())::text || ':'::text) || (clock_timestamp())::text)) PLACING '4'::text FROM 13) PLACING to_hex((floor(((random() * (((11 - 8) + 1))::double precision) + (8)::double precision)))::integer) FROM 17))::cstring)"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('personalizationAnswers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mfaEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('mfaSecret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mfaRecoveryCodes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastActiveAt', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('roleSlug', sa.VARCHAR(length=128), server_default=sa.text("'global:member'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roleSlug'], ['role.slug'], name='FK_eaea92ee7bfb9c1b6cd01505d56'),
    sa.PrimaryKeyConstraint('id', name='PK_ea8f538c94b6e352418254ed6474a81f'),
    sa.UniqueConstraint('email', name='UQ_e12875dfb3b1d92d7d7c5377e2', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('user_role_idx', 'user', ['roleSlug'], unique=False)
    op.create_table('workflow_statistics',
    sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('latestEvent', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('rootCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='fk_workflow_statistics_workflow_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflowId', 'name', name='pk_workflow_statistics')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apiKey', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='FK_e131705cbbc8fb589889b02d457', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_978fa5caa3468f463dac9d92e69')
    )
    op.create_index('IDX_63d7bbae72c767cf162d459fcc', 'user_api_keys', ['userId', 'label'], unique=False)
    op.create_index('IDX_1ef35bac35d20bdae979d917a3', 'user_api_keys', ['apiKey'], unique=False)
    op.create_table('execution_annotations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('execution_annotations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('executionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['executionId'], ['execution_entity.id'], name='FK_97f863fa83c4786f19565084960', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_7afcf93ffa20c4252869a7c6a23'),
    postgresql_ignore_search_path=False
    )
    op.create_index('IDX_97f863fa83c4786f1956508496', 'execution_annotations', ['executionId'], unique=False)
    op.create_table('workflow_history',
    sa.Column('versionId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authors', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('connections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='FK_1e31657f5fe46816c34be7c1b4b', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('versionId', name='PK_b6572dd6173e4cd06fe79937b58')
    )
    op.create_index('IDX_1e31657f5fe46816c34be7c1b4', 'workflow_history', ['workflowId'], unique=False)
    op.create_table('folder_tag',
    sa.Column('folderId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tagId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folderId'], ['folder.id'], name='FK_94a60854e06f2897b2e0d39edba', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagId'], ['tag_entity.id'], name='FK_dc88164176283de80af47621746', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folderId', 'tagId', name='PK_27e4e00852f6b06a925a4d83a3e')
    )
    op.create_table('insights_metadata',
    sa.Column('metaId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('workflowName', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('projectName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_2375a1eda085adb16b24615b69c', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='FK_1d8ab99d5861c9388d2dc1cf733', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('metaId', name='PK_f448a94c35218b6208ce20cf5a1'),
    postgresql_ignore_search_path=False
    )
    op.create_index('IDX_1d8ab99d5861c9388d2dc1cf73', 'insights_metadata', ['workflowId'], unique=False)
    op.create_table('execution_entity',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('execution_entity_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('finished', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('retryOf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('retrySuccessId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('startedAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('stoppedAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('waitTill', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('deletedAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='fk_execution_entity_workflow_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_e3e63bbf986767844bbe1166d4e'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_execution_entity_workflow_id_started_at', 'execution_entity', ['workflowId', 'startedAt'], unique=False, postgresql_where='(("startedAt" IS NOT NULL) AND ("deletedAt" IS NULL))')
    op.create_index('idx_execution_entity_wait_till_status_deleted_at', 'execution_entity', ['waitTill', 'status', 'deletedAt'], unique=False, postgresql_where='(("waitTill" IS NOT NULL) AND ("deletedAt" IS NULL))')
    op.create_index('idx_execution_entity_stopped_at_status_deleted_at', 'execution_entity', ['stoppedAt', 'status', 'deletedAt'], unique=False, postgresql_where='(("stoppedAt" IS NOT NULL) AND ("deletedAt" IS NULL))')
    op.create_index('IDX_execution_entity_deletedAt', 'execution_entity', ['deletedAt'], unique=False)
    op.create_table('execution_annotation_tags',
    sa.Column('annotationId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tagId', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['annotationId'], ['execution_annotations.id'], name='FK_c1519757391996eb06064f0e7c8', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagId'], ['annotation_tag_entity.id'], name='FK_a3697779b366e131b2bbdae2976', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotationId', 'tagId', name='PK_979ec03d31294cca484be65d11f')
    )
    op.create_index('IDX_c1519757391996eb06064f0e7c', 'execution_annotation_tags', ['annotationId'], unique=False)
    op.create_index('IDX_a3697779b366e131b2bbdae297', 'execution_annotation_tags', ['tagId'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('icon', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_4d68b1358bb5b766d3e78f32f57'),
    postgresql_ignore_search_path=False
    )
    op.create_table('credentials_entity',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('isManaged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='credentials_entity_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('pk_credentials_entity_id', 'credentials_entity', ['id'], unique=False)
    op.create_index('idx_07fde106c0b471d8cc80a64fc8', 'credentials_entity', ['type'], unique=False)
    op.create_table('role',
    sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='Unique identifier of the role for example: "global:owner"'),
    sa.Column('displayName', sa.TEXT(), autoincrement=False, nullable=True, comment='Name used to display in the UI'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Text describing the scope in more detail of users'),
    sa.Column('roleType', sa.TEXT(), autoincrement=False, nullable=True, comment='Type of the role, e.g., global, project, or workflow'),
    sa.Column('systemRole', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Indicates if the role is managed by the system and cannot be edited'),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('slug', name='PK_35c9b140caaf6da09cfabb0d675'),
    postgresql_ignore_search_path=False
    )
    op.create_table('processed_data',
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('context', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='FK_06a69a7032c97a763c2c7599464', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflowId', 'context', name='PK_ca04b9d8dc72de268fe07a65773')
    )
    op.create_table('event_destinations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('destination', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event_destinations_pkey')
    )
    op.create_table('webhook_entity',
    sa.Column('webhookPath', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('webhookId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pathLength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workflowId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflowId'], ['workflow_entity.id'], name='fk_webhook_entity_workflow_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('webhookPath', 'method', name='PK_b21ace2e13596ccd87dc9bf4ea6')
    )
    op.create_index('idx_16f4436789e804e3e1c9eeb240', 'webhook_entity', ['webhookId', 'method', 'pathLength'], unique=False)
    op.create_table('variables',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), server_default=sa.text("'string'::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='variables_pkey'),
    sa.UniqueConstraint('key', name='variables_key_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('pk_variables_id', 'variables', ['id'], unique=False)
    op.create_table('role_scope',
    sa.Column('roleSlug', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('scopeSlug', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['roleSlug'], ['role.slug'], name='FK_role', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scopeSlug'], ['scope.slug'], name='FK_scope', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roleSlug', 'scopeSlug', name='PK_role_scope')
    )
    op.create_index('IDX_role_scope_scopeSlug', 'role_scope', ['scopeSlug'], unique=False)
    op.create_table('insights_by_period',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('metaId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False, comment='0: time_saved_minutes, 1: runtime_milliseconds, 2: success, 3: failure'),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('periodUnit', sa.INTEGER(), autoincrement=False, nullable=False, comment='0: hour, 1: day, 2: week'),
    sa.Column('periodStart', postgresql.TIMESTAMP(timezone=True, precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['metaId'], ['insights_metadata.metaId'], name='FK_6414cfed98daabbfdd61a1cfbc0', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_b606942249b90cc39b0265f0575')
    )
    op.create_index('IDX_60b6a84299eeb3f671dfec7693', 'insights_by_period', ['periodStart', 'type', 'periodUnit', 'metaId'], unique=False)
    op.create_table('annotation_tag_entity',
    sa.Column('id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_69dfa041592c30bbc0d4b84aa00')
    )
    op.create_index('IDX_ae51b54c4bb430cf92f48b623f', 'annotation_tag_entity', ['name'], unique=False)
    op.create_table('auth_identity',
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('providerId', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('providerType', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='auth_identity_userId_fkey'),
    sa.PrimaryKeyConstraint('providerId', 'providerType', name='auth_identity_pkey')
    )
    op.create_table('shared_credentials',
    sa.Column('credentialsId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credentialsId'], ['credentials_entity.id'], name='FK_416f66fc846c7c442970c094ccf', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_812c2852270da1247756e77f5a4', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credentialsId', 'projectId', name='PK_8ef3a59796a228913f251779cff')
    )
    op.create_table('execution_data',
    sa.Column('executionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflowData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['executionId'], ['execution_entity.id'], name='execution_data_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('executionId', name='execution_data_pkey')
    )
    op.create_table('folder',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('parentFolderId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parentFolderId'], ['folder.id'], name='FK_804ea52f6729e3940498bd54d78', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_a8260b0b36939c6247f385b8221', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_6278a41a706740c94c02e288df8'),
    postgresql_ignore_search_path=False
    )
    op.create_index('IDX_14f68deffaf858465715995508', 'folder', ['projectId', 'id'], unique=False)
    op.create_table('installed_packages',
    sa.Column('packageName', sa.VARCHAR(length=214), autoincrement=False, nullable=False),
    sa.Column('installedVersion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('authorName', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('authorEmail', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('packageName', name='PK_08cc9197c39b028c1e9beca225940576fd1a5804')
    )
    op.create_table('execution_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('executionId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['executionId'], ['execution_entity.id'], name='FK_31d0b4c93fb85ced26f6005cda3', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_17a0b6284f8d626aae88e1c16e4')
    )
    op.create_index('IDX_cec8eea3bf49551482ccb4933e', 'execution_metadata', ['executionId', 'key'], unique=False)
    op.create_table('workflow_entity',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nodes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('connections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('staticData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('pinData', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('versionId', sa.CHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('triggerCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parentFolderId', sa.VARCHAR(length=36), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('isArchived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parentFolderId'], ['folder.id'], name='fk_workflow_parent_folder', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_entity_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('pk_workflow_entity_id', 'workflow_entity', ['id'], unique=False)
    op.create_index('IDX_workflow_entity_name', 'workflow_entity', ['name'], unique=False)
    op.create_table('data_table',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], name='FK_c2a794257dee48af7c9abf681de', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_e226d0001b9e6097cbfe70617cb'),
    sa.UniqueConstraint('projectId', 'name', name='UQ_b23096ef747281ac944d28e8b0d', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test_case_execution',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('testRunId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('executionId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('runAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('completedAt', postgresql.TIMESTAMP(timezone=True, precision=3), autoincrement=False, nullable=True),
    sa.Column('errorCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('errorDetails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('inputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outputs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execution_entity.id'], name='FK_e48965fac35d0f5b9e7f51d8c44', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['testRunId'], ['test_run.id'], name='FK_8e4b4774db42f1e6dda3452b2af', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_90c121f77a78a6580e94b794bce')
    )
    op.create_index('IDX_8e4b4774db42f1e6dda3452b2a', 'test_case_execution', ['testRunId'], unique=False)
    op.create_table('tag_entity',
    sa.Column('name', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True, precision=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tag_entity_pkey')
    )
    op.create_index('pk_tag_entity_id', 'tag_entity', ['id'], unique=False)
    op.create_index('idx_812eb05f7451ca757fb98444ce', 'tag_entity', ['name'], unique=False)
    op.drop_index(op.f('ix_chat_timeline_events_type'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_thread_id'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_status'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_organization_id'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_order_index'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_id'), table_name='chat_timeline_events')
    op.drop_index(op.f('ix_chat_timeline_events_created_at'), table_name='chat_timeline_events')
    op.drop_table('chat_timeline_events')
    op.drop_index(op.f('ix_chat_files_user_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_thread_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_organization_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_created_at'), table_name='chat_files')
    op.drop_table('chat_files')
    # ### end Alembic commands ###
