"""Add cnpj_cpf to organizations

Revision ID: 7297349ace40
Revises: 
Create Date: 2025-10-11 17:33:19.176187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7297349ace40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('organizations', sa.Column('cnpj_cpf', sa.String(length=20), nullable=True))
    
    # Update existing records with default values
    op.execute("""
        UPDATE organizations 
        SET cnpj_cpf = 'TEMP-' || id::text 
        WHERE cnpj_cpf IS NULL
    """)
    
    # Now make it NOT NULL and unique
    op.alter_column('organizations', 'cnpj_cpf', nullable=False)
    op.create_index(op.f('ix_organizations_cnpj_cpf'), 'organizations', ['cnpj_cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_cnpj_cpf'), table_name='organizations')
    op.drop_column('organizations', 'cnpj_cpf')
    # ### end Alembic commands ###
