"""replace_timeline_with_checklist

Revision ID: 8c9826281c3e
Revises: 155d5d9380f5
Create Date: 2026-01-15 20:00:02.517815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c9826281c3e'
down_revision = '155d5d9380f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_checklist_items_id'), 'process_checklist_items', ['id'], unique=False)
    op.drop_index('ix_process_timeline_entries_id', table_name='process_timeline_entries')
    op.drop_table('process_timeline_entries')
    op.drop_index('ix_chat_timeline_events_created_at', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_id', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_order_index', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_organization_id', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_status', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_thread_id', table_name='chat_timeline_events')
    op.drop_index('ix_chat_timeline_events_type', table_name='chat_timeline_events')
    op.drop_table('chat_timeline_events')
    op.add_column('processes', sa.Column('in_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processes', 'in_type')
    op.create_table('chat_timeline_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STAGE', 'SYSTEM', 'FILE', 'DECISION', 'AI_PROCESSING', 'ERROR', name='timelineeventtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'ERROR', 'CANCELLED', name='timelineeventstatus'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='chat_timeline_events_organization_id_fkey'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name='chat_timeline_events_thread_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_timeline_events_pkey')
    )
    op.create_index('ix_chat_timeline_events_type', 'chat_timeline_events', ['type'], unique=False)
    op.create_index('ix_chat_timeline_events_thread_id', 'chat_timeline_events', ['thread_id'], unique=False)
    op.create_index('ix_chat_timeline_events_status', 'chat_timeline_events', ['status'], unique=False)
    op.create_index('ix_chat_timeline_events_organization_id', 'chat_timeline_events', ['organization_id'], unique=False)
    op.create_index('ix_chat_timeline_events_order_index', 'chat_timeline_events', ['order_index'], unique=False)
    op.create_index('ix_chat_timeline_events_id', 'chat_timeline_events', ['id'], unique=False)
    op.create_index('ix_chat_timeline_events_created_at', 'chat_timeline_events', ['created_at'], unique=False)
    op.create_table('process_timeline_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('EM_ANDAMENTO', 'AGUARDANDO_ANALISE', 'APROVADO', 'PENDENTE', 'ATRASADO', 'CANCELADO', name='processstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], name='process_timeline_entries_process_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='process_timeline_entries_pkey')
    )
    op.create_index('ix_process_timeline_entries_id', 'process_timeline_entries', ['id'], unique=False)
    op.drop_index(op.f('ix_process_checklist_items_id'), table_name='process_checklist_items')
    op.drop_table('process_checklist_items')
    # ### end Alembic commands ###
