"""Ensure users table has last_login_at field

Revision ID: 9f787ba2a678
Revises: 7297349ace40
Create Date: 2025-10-13 21:50:33.489274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f787ba2a678'
down_revision = '7297349ace40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
