"""sync_subscription_schema

Revision ID: ea5251f8fbae
Revises: 25f9330d6de4
Create Date: 2025-12-05 23:31:29.645885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea5251f8fbae'
down_revision = '25f9330d6de4'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added: Create Enums
    licensestatus = postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='licensestatus')
    licensestatus.create(op.get_bind(), checkfirst=True)

    subscriptionstatus = postgresql.ENUM('ACTIVE', 'INACTIVE', 'PAST_DUE', 'CANCELED', 'TRIAL', name='subscriptionstatus')
    subscriptionstatus.create(op.get_bind(), checkfirst=True)

    op.create_index(op.f('ix_flow_metrics_id'), 'flow_metrics', ['id'], unique=False)
    op.add_column('licenses', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='licensestatus'), nullable=False))
    op.add_column('licenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('licenses', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('licenses', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('licenses_license_key_key', 'licenses', type_='unique')
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_organization_id'), 'licenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_licenses_status'), 'licenses', ['status'], unique=False)
    op.create_foreign_key(None, 'licenses', 'users', ['user_id'], ['id'])
    op.drop_column('licenses', 'license_key')
    op.drop_column('licenses', 'max_users')
    op.drop_column('licenses', 'expiry_date')
    op.drop_column('licenses', 'is_active')
    op.drop_column('licenses', 'issued_date')
    op.drop_column('licenses', 'license_type')
    op.drop_index('ix_municipal_instructions_current', table_name='municipal_instructions')
    op.drop_index('ix_municipal_instructions_municipality', table_name='municipal_instructions')
    op.create_index(op.f('ix_municipal_instructions_municipality'), 'municipal_instructions', ['municipality'], unique=False)
    op.create_index(op.f('ix_municipal_instructions_id'), 'municipal_instructions', ['id'], unique=False)
    op.create_index(op.f('ix_municipal_instructions_is_current'), 'municipal_instructions', ['is_current'], unique=False)
    op.create_index(op.f('ix_org_connections_id'), 'org_connections', ['id'], unique=False)
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.add_column('plans', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('plans', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('plans', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.alter_column('plans', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.drop_column('plans', 'price_yearly')
    op.drop_column('plans', 'price_monthly')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'PAST_DUE', 'CANCELED', 'TRIAL', name='subscriptionstatus'),
               existing_nullable=False,
               postgresql_using='status::subscriptionstatus')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'billing_cycle')
    op.drop_column('subscriptions', 'end_date')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('billing_cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'PAST_DUE', 'CANCELED', 'TRIAL', name='subscriptionstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('subscriptions', 'canceled_at')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_unique_constraint('roles_name_key', 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('plans', sa.Column('price_monthly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('price_yearly', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.alter_column('plans', 'features',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('plans', 'max_users',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('plans', 'is_system')
    op.drop_column('plans', 'currency')
    op.drop_column('plans', 'price')
    op.drop_column('plans', 'display_name')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_org_connections_id'), table_name='org_connections')
    op.drop_index(op.f('ix_municipal_instructions_is_current'), table_name='municipal_instructions')
    op.drop_index(op.f('ix_municipal_instructions_id'), table_name='municipal_instructions')
    op.drop_index(op.f('ix_municipal_instructions_municipality'), table_name='municipal_instructions')
    op.create_index('ix_municipal_instructions_municipality', 'municipal_instructions', ['municipality', 'state'], unique=False)
    op.create_index('ix_municipal_instructions_current', 'municipal_instructions', ['is_current'], unique=False)
    op.add_column('licenses', sa.Column('license_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('licenses', sa.Column('issued_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('licenses', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('licenses', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('licenses', sa.Column('license_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_index(op.f('ix_licenses_status'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_organization_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.create_unique_constraint('licenses_license_key_key', 'licenses', ['license_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('licenses', 'deactivated_at')
    op.drop_column('licenses', 'activated_at')
    op.drop_column('licenses', 'user_id')
    op.drop_column('licenses', 'status')
    op.drop_index(op.f('ix_flow_metrics_id'), table_name='flow_metrics')
    # ### end Alembic commands ###
